### ISSUE TITLE
Add key markers to map?

### ISSUE THREAD

**Issue by Temetz** [EisFrei/IngressLiveInventory#1]
Hi,

Would you be interested in integrating some functionality from this code to your code?
https://github.com/Temetz/IngressPlayerInventoryMap/blob/main/playerInventoryMap.user.js

This would allow displaying portal markers on the portals the player has a key for.
Its based on your portal history plugin.

I think it would be fairly simple to just add this sort of functionality to your code.
Simply adding a layergroup and adding markers to it as the inventory is loaded.

Might be able to make this feature later tonight if interested.

Sample screenshot:
![image](https://user-images.githubusercontent.com/8721037/107499760-06eafb80-6b9e-11eb-8254-40011cf14984.png)

**Comment by EisFrei** [comment]
I added a key icon layer, but chose a different way of displaying them.

It's a key icon in the center of the portal ;)
