### ISSUE TITLE
Line 243

### ISSUE THREAD

**Issue by DarkTechnician** [EisFrei/IngressLiveInventory#5]
Line 242 compares sA and sb. sb is undefined, so that always returns false.

[https://github.com/EisFrei/IngressLiveInventory/blob/45c7cea2a6ff3dc028ed071f0bc451ac2ec53cc9/liveInventory.user.js#L243](url)

From: `if (sA === sb) {`
To: `if (sA === sB) {`

**Comment by EisFrei** [comment]
Whoops. Fixed in 0.0.9
