### ISSUE TITLE
Feature Request: View containing capsule for keys in portal detail

### ISSUE THREAD

**Issue by tehstone** [EisFrei/IngressLiveInventory#6]
Currently, when viewing portal detail the number of keys will be displayed but no other info.
Displaying the capsule(s) the key is in would be a great extra bit of info rather than opening the inventory view and scrolling through to find the portal name.

**Comment by EisFrei** [comment]
Good idea. I'll add it this evening

**Comment by EisFrei** [comment]
Capsule information has been added to portal detail view
